name: ModChecker
version: 1.0.0
main: ru.musd348.modchecker.ModChecker
api-version: '1.20'
author: musd348
description: Plugin for checking client mods, version and type

commands:
  checkmods:
    description: Check player mods, client and version
    usage: /checkmods [player]
    permission: modchecker.use

permissions:
  modchecker.use:
    description: Allows using /checkmods command
    default: op
