name: ModChecker
version: '${project.version}'
main: ru.musd348.modchecker.ModChecker
api-version: '1.21'
author: musd348
description: Проверка клиента, версии игры и списка модов у игроков
website: https://github.com/gulp-tech/LMspectator

commands:
  checkmods:
    description: Показать клиент, версию игры и список модов игрока
    usage: /checkmods <ник_игрока>
    aliases: [checkmod, mods, cm]
    permission: modchecker.use
    permission-message: <red>У вас нет прав для использования этой команды.</red>

permissions:
  modchecker.use:
    description: Доступ к команде /checkmods
    default: op
